services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    container_name: checkin_api
    ports:
      - "8080:8080"
    depends_on: # Wait for the db to be healthy before starting
      db:
        condition: service_healthy
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LABOR_SQS_QUEUE_URL=http://localstack:4566/000000000000/labor-queue
      - EMAIL_SQS_QUEUE_URL=http://localstack:4566/000000000000/email-queue
      - AWS_ENDPOINT=http://localstack:4566
      - IS_LOCAL_DEV=true
    restart: on-failure
    networks:
      - app-network
      - db-network

  checkin-worker:
    build:
      context: .
      dockerfile: ./Dockerfile.checkin-worker      
    container_name: checkin_worker
    depends_on: # Wait for dependencies to be ready before starting
      db:
        condition: service_healthy
      localstack:
        condition: service_started
      legacy-api:
        condition: service_started
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LABOR_SQS_QUEUE_URL=http://localstack:4566/000000000000/labor-queue
      - LEGACY_API_URL=http://legacy-api:8081
      - AWS_ENDPOINT=http://localstack:4566
      - IS_LOCAL_DEV=true
    restart: on-failure
    networks:
      - app-network
      - db-network

  email-worker:
    build:
      context: .
      dockerfile: ./Dockerfile.email-worker
    container_name: email_worker
    depends_on: # Wait for dependencies to be ready before starting
      db:
        condition: service_healthy
      localstack:
        condition: service_started
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - EMAIL_SQS_QUEUE_URL=http://localstack:4566/000000000000/email-queue
      - AWS_ENDPOINT=http://localstack:4566
      - IS_LOCAL_DEV=true
    restart: on-failure
    networks:
      - app-network
      - db-network

  db:
    image: postgres:13-alpine
    container_name: checkin_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=checkin_db
    ports:
      - "5432:5432"
    volumes:
      - checkin_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d checkin_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - db-network

  localstack:
    image: localstack/localstack
    container_name: checkin_localstack
    ports:
      - "4566:4566" # Main endpoint for all services
    environment:
      - SERVICES=sqs
      - DEBUG=1
    volumes:
      - ./tools/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
    networks:
      - app-network

  legacy-api:
    build:
      context: .
      dockerfile: ./tools/legacy-api-mock/Dockerfile
    container_name: checkin_legacy_api
    ports:
      - "8081:8081"
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: checkin_jaeger
    ports:
      - "16686:16686" # Web UI
      - "4317:4317"   # OTLP gRPC
    networks:
      - app-network

volumes:
  checkin_db_data:

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
    internal: true
